name: Create release and upload binaries on tagging.

on:
  push:
    tags:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v2
      with:
        java-version: '21'
        distribution: 'adopt'

    - name: Install clojure tools
      uses: DeLaGuardo/setup-clojure@10.1
      with:
        lein: latest

    - name: Generate binaries
      run: |
        lein bin
        lein uberjar
        find . -name jmx-dump

    - name: Extract version from tag
      id: extract_version
      run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
    
    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        files: |
          ./target/jmx-dump-${{ steps.extract_version.outputs.VERSION }}-standalone.jar
          ./target/jmx-dump
